spring:
  datasource:
    ###普通用户数据库
#      url: jdbc:mysql://localhost:3306/mysql
#      username: root
#      password: tcc123456
#      driver-class-name: com.mysql.jdbc.Driver

      ###会员数据库
        member:
          jdbc-url: jdbc:mysql://localhost:3306/member
          username: root
          password: tcc123456
          driver-class-name: com.mysql.jdbc.Driver

         ###订单数据库
        order:
          jdbc-url: jdbc:mysql://localhost:3306/order
          username: root
          password: tcc123456
          driver-class-name: com.mysql.jdbc.Driver