#server:
#  port: 8080
#  servlet:
#    session:
#      timeout: 1800s
spring:
  session:
    store-type: redis
    redis:
      host: localhost
      port: 6379

server:
  port: 8081
  servlet:
    session:
      timeout: 60s